#!/usr/bin/env python3
"""Collect release notices from the Windows dependency graph and local source licenses."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[1]
TAGS = 'desktop,wv2runtime.browser,production'
NAMES = {'license', 'licence', 'copying', 'notice', 'patents', 'copyright'}


def run(*args):
    env = dict(os.environ, GOOS='windows', GOARCH='amd64', CGO_ENABLED='0')
    return subprocess.check_output(args, cwd=ROOT, env=env, text=True)


def objects(text):
    decoder = json.JSONDecoder()
    while text.strip():
        text = text.lstrip()
        value, end = decoder.raw_decode(text)
        yield value
        text = text[end:]


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def notice_files(root):
    return sorted(p for p in root.rglob('*') if p.is_file()
                  and p.name.lower().split('.')[0] in NAMES
                  and 'node_modules' not in p.parts and '.git' not in p.parts)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--binary', type=Path, help='Also verify modules and toolchain against a built EXE')
    parser.add_argument('--check', action='store_true', help='Fail if committed output differs')
    args = parser.parse_args()
    packages = list(objects(run('go', 'list', '-deps', '-json', '-tags', TAGS, '.')))
    modules = {p['Module']['Path']: p['Module'] for p in packages
               if p.get('Module') and not p['Module'].get('Main')}
    if any(m.get('Replace') for m in modules.values()):
        raise SystemExit('Replaced dependencies require a manual notice review.')
    go_version = run('go', 'env', 'GOVERSION').strip()
    if args.binary:
        binary = run('go', 'version', '-m', str(args.binary.resolve()))
        actual = {}
        for line in binary.splitlines():
            fields = line.split()
            if fields and fields[0] == 'dep':
                actual[fields[1]] = fields[2]
        expected = {name: m['Version'] for name, m in modules.items()}
        if actual != expected or binary.splitlines()[0].split()[-1] != go_version:
            raise SystemExit('EXE dependencies/toolchain differ from the notice source graph.')
        for setting in ('GOOS=windows', 'GOARCH=amd64', 'CGO_ENABLED=0', '-tags=' + TAGS):
            if setting not in binary:
                raise SystemExit('Unexpected EXE build setting: ' + setting)
    sections = ['''THIRD-PARTY NOTICES

Generated by scripts/generate_notices.py for Windows amd64, CGO disabled,
build tags: desktop,wv2runtime.browser,production.

This file preserves license and attribution material from the selected Go
modules and runtime, plus frontend and Unicode notices. Module-wide notices
may also cover source files not linked into this target. Inclusion of a notice
does not mean every feature or subcomponent of that module is distributed.
Original license texts below govern their respective components; this file
is not a replacement license or a certification of legal compliance.

The app's own MIT license is supplied separately as LICENSE and in the app.
Windows system tools (DISM, SFC, Defender, shutdown, Explorer and system DLLs)
are invoked on the user's computer; their binaries are not shipped by this app.
The Microsoft WebView2 runtime is installed separately. This build uses the
browser installation strategy and does not ship the Microsoft bootstrapper.
See the Microsoft section below for runtime notices and terms.
''']
    inventory = {'target': 'windows/amd64', 'cgo': False, 'tags': TAGS,
                 'go_version': go_version, 'components': []}

    def add(name, version, root, files, scope):
        if not files:
            raise SystemExit('No license material found for ' + name)
        record = {'name': name, 'version': version, 'scope': scope, 'notices': []}
        sections.append('\n' + '=' * 78 + '\n' + name + ' ' + version + '\n' + scope + '\n')
        for path in files:
            rel = str(path.relative_to(root)).replace('\\', '/')
            text = path.read_text(encoding='utf-8-sig')
            sections.append('\n--- ' + rel + ' ---\n\n' + text.rstrip() + '\n')
            record['notices'].append({'path': rel, 'sha256': digest(path)})
        inventory['components'].append(record)

    goroot = Path(run('go', 'env', 'GOROOT').strip())
    go_files = {goroot / 'LICENSE', goroot / 'PATENTS'}
    # Include package-specific and vendored notices for the selected standard packages.
    for package in packages:
        if package.get('Standard'):
            directory = Path(package['Dir'])
            while directory != goroot and goroot in directory.parents:
                go_files.update(f for f in directory.iterdir() if f.is_file()
                                and f.name.lower().split('.')[0] in NAMES)
                directory = directory.parent
    add('Go runtime and standard library', go_version, goroot, sorted(go_files),
        'Runtime source notices, including selected package/vendor notices. CGO and BoringCrypto are disabled; any BoringSSL notice is retained conservatively for that source package.')
    for name, module in sorted(modules.items()):
        root = Path(module['Dir'])
        add(name, module['Version'], root, notice_files(root),
            'Go module selected by the Windows production dependency graph; unmodified upstream source.')

    vite = ROOT / 'frontend/node_modules/vite'
    version = json.loads((vite / 'package.json').read_text())['version']
    add('Vite', version, vite, [vite / 'LICENSE.md'],
        'Build-time tool. Includes upstream bundled notices conservatively; the generated frontend may include the modulepreload helper. Node.js and the Vite server are not shipped.')
    add('Unicode data', 'license snapshot 2026-09-12', ROOT / 'legal',
        [ROOT / 'legal/UNICODE-LICENSE.txt'],
        'Unicode tables are used by Go and dependencies including uniseg. Source: https://www.unicode.org/license.txt')
    sections.append('\n' + '=' * 78 + '\n' + (ROOT / 'legal/MICROSOFT-WEBVIEW2-NOTICE.txt').read_text())
    add('Microsoft Edge WebView2 Runtime terms', 'snapshot 2026-09-12', ROOT / 'legal',
        [ROOT / 'legal/MICROSOFT-WEBVIEW2-TERMS.txt'],
        'Official Evergreen distribution terms: https://developer.microsoft.com/microsoft-edge/api/eula/webview2 ; HTML converted to plain text without changing the wording.')
    bootstrap = Path(modules['github.com/wailsapp/wails/v2']['Dir']) / 'internal/webview2runtime/MicrosoftEdgeWebview2Setup.exe'
    inventory['webview2_bootstrapper'] = {'source_module': 'github.com/wailsapp/wails/v2',
        'version': modules['github.com/wailsapp/wails/v2']['Version'], 'path': 'internal/webview2runtime/MicrosoftEdgeWebview2Setup.exe',
        'size': bootstrap.stat().st_size, 'sha256': digest(bootstrap),
        'distribution': 'not shipped; retained in upstream Wails source cache only'}
    if args.binary and bootstrap.read_bytes() in args.binary.read_bytes():
        raise SystemExit('Unexpected Microsoft bootstrapper embedded in the EXE.')
    outputs = {ROOT / 'THIRD_PARTY_NOTICES.txt': '\n'.join(sections),
               ROOT / 'legal/dependency-inventory.json': json.dumps(inventory, indent=2, ensure_ascii=False) + '\n'}
    for path, text in outputs.items():
        if args.check:
            if not path.exists() or path.read_text() != text:
                raise SystemExit('Outdated generated file: ' + str(path.relative_to(ROOT)))
        else:
            path.write_text(text)
    print(('Verified' if args.check else 'Generated') + f' notices for {len(modules)} Go modules, {go_version}, Vite and Unicode.')


if __name__ == '__main__':
    main()
